variables:
  IMAGE_NAME: registry.gitlab.com/jules_sbts/next-demo

stages:
  - build
  - publish

build-job:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
  only:
    - main

publish-job:
  stage: publish
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker pull $IMAGE_NAME:$CI_COMMIT_SHORT_SHA || echo "Image not found, skipping pull"
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest
  dependencies:
    - build-job
  only:
    - main
