variables:
  IMAGE_NAME: registry.gitlab.com/jules_sbts/next-demo

stages:
  - build
  - publish

build-job:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker buildx build --platform linux/amd64 -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker save $IMAGE_NAME:$CI_COMMIT_SHORT_SHA -o image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 hour
  only:
    - main

publish-job:
  stage: publish
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker load -i image.tar
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest
  dependencies:
    - build-job
  only:
    - main
